# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kmeans_hartigan <- function(data, centers, weight) {
    .Call('_SWKM_kmeans_hartigan', PACKAGE = 'SWKM', data, centers, weight)
}

